### ISSUE TITLE
Panic in firmware

### ISSUE THREAD

**Issue by huynhphucloi** [chcbaram/esp32-s3#1]
Hello!
i tried your source code. I have panic problem for using firmware:
<img width="992" alt="Screenshot 2023-07-09 at 06 26 00" src="https://github.com/chcbaram/esp32-s3/assets/64252151/b6891151-31d7-48e0-ad69-65450123ba7d">
<img width="997" alt="Screenshot 2023-07-09 at 06 26 28" src="https://github.com/chcbaram/esp32-s3/assets/64252151/065869a7-d5f4-4050-a61c-a7164d5d564d">
maybe the problem is for function void logPrintf(const char *fmt, ...). Do you have any solution to this problem? Thanks

**Comment by chcbaram** [comment]
> 

I didn't have the same problem like you. 
I think you could try change the option in menuconfig for you hardware.

**Comment by huynhphucloi** [comment]
thanks for your reply. I found the cause because the variable print_buf[256] points to the section not existing (.non_cache). 

<img width="657" alt="Screenshot 2023-07-13 at 21 58 07" src="https://github.com/chcbaram/esp32-s3/assets/64252151/a79aa26a-67a4-4a93-8ae9-42ac3e389b91">

just change this point and it works properly.

**Comment by chcbaram** [comment]
Great. 

And I found you tried stm32cli for python. 
I am not goot at python so I learned from your code. 
Thanks.

**Comment by huynhphucloi** [comment]
Great. 
I have watched your youtube videos as well as your blog posts. Very useful knowledge. 
I learn many things from you. 
Thank you very much
